"""
API定义模块 - 全部API端点定义(截至2025年）
"""
from config import API_KEY

API_DEFINITIONS = [
    {"name": "[通用] URI访问-内容协商", "method": "GET",
     "url": "http://data.library.sh.cn/entity/architecture/yyknd1unz1xonxp7.json"},
    {"name": "[通用] URI访问-JSON-LD", "method": "GET",
     "url": "https://data1.library.sh.cn/data/jsonld", "params": {
        "uri": "http://data.library.sh.cn/entity/architecture/yyknd1unz1xonxp7",
        "key": API_KEY}},
    {"name": "[宋庆龄] 文献搜索", "method": "GET",
     "url": "http://www.sclrd.net.cn/api/search/competitionSearch",
     "params": {"key": API_KEY, "searchContent": "TI:孙中山",
                "categories": "article"}},
    {"name": "[PDF] 获取开放下载书目列表", "method": "POST",
     "url": "https://data1.library.sh.cn/service_pdf_race/race/pdf/list",
     "json_data": {"dbname": "mgts", "title": "教育", "pageSize": 1,
                   "apiKey": API_KEY}},
    {"name": "[PDF] 获取PDF资源目录信息", "method": "POST",
     "url": "https://data1.library.sh.cn/service_pdf_race/race/pdf/info",
     "json_data": {"dbname": "mgts", "value": "00246247", "apiKey": API_KEY}},
    {"name": "[PDF] 获取PDF资源 (文件流)", "method": "POST",
     "url": "https://data1.library.sh.cn/service_pdf_race/race/pdf/stream",
     "json_data": {"dbname": "jp", "itemId": "48343", "pageNo": "1",
                   "apiKey": API_KEY}, "expect_json": False,
     "file_ext": ".pdf"},
    {"name": "[韬奋] 机构年表", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/zoutaofen/getOrgYearListInterface",
     "params": {"key": API_KEY, "keyword": "生活书店"}},
    {"name": "[韬奋] 人物年表", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/zoutaofen/getHumanYearListInterface",
     "params": {"key": API_KEY, "keyword": "邹韬奋"}},
    {"name": "[韬奋] 图书列表", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/zoutaofen/getBookInterface",
     "params": {"key": API_KEY, "keyword": "邹韬奋"}},
    {"name": "[韬奋] 韬奋关系", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/zoutaofen/getRelationInterFace",
     "params": {"key": API_KEY}},
    {"name": "[碑帖] 碑帖检索", "method": "POST",
     "url": f"https://data1.library.sh.cn/webapi/beitie/search?key={API_KEY}",
     "json_data": {"searchType": "1", "freetext": "化度寺",
                   "pager": {"pageth": 1, "pageSize": 1}}},
    {"name": "[碑帖] 碑帖详情", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/beitie/info", "params": {
        "uri": "http://data.library.sh.cn/bt/resource/work/f69uvv5c45n6df2j",
        "key": API_KEY}},
    {"name": "[碑帖] 单字检索", "method": "POST",
     "url": f"https://data1.library.sh.cn/webapi/beitie/danzi/search?key={API_KEY}",
     "json_data": {"freetext": "文",
                   "pager": {"pageth": 1, "pageSize": 1}}},
    {"name": "[碑帖] 背景知识列表", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/beitie/beitie/background",
     "params": {"pageSize": 1, "key": API_KEY}},
    {"name": "[碑帖] 名家列表", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/beitie/person/search",
     "params": {"temporal": "唐", "pageSize": 1, "key": API_KEY}},
    {"name": "[碑帖] 名家详情", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/beitie/person/info", "params": {
        "uri": "http://data.library.sh.cn/entity/person/ww68ccx56mn70140",
        "key": API_KEY}},
    {"name": "[碑帖] 名家主要作品列表", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/beitie/person/work", "params": {
        "uri": "http://data.library.sh.cn/entity/person/ww68ccx56mn70140",
        "key": API_KEY}},
    {"name": "[刻工] 刻工名录列表", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/kg/list",
     "params": {"key": API_KEY, "freetext": "陈"}},
    {"name": "[刻工] 刻工名录详情", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/kg/detail", "params": {
        "personUri": "http://data.library.sh.cn/entity/person/azxszcygtdotqxxh",
        "key": API_KEY}},
    {"name": "[年华机构] 上海年华机构列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/whzk/webapi/org/list",
     "params": {"freetext": "上海", "pageSize": 1, "key": API_KEY}},
    {"name": "[年华机构] 上海年华机构详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/whzk/webapi/org/detail",
     "params": {
         "uri": "http://data.library.sh.cn/entity/organization/0z7jo5b5rqrnn15t",
         "key": API_KEY}},
    {"name": "[舆图] 舆图目录列表", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/yutu/list",
     "params": {"freetext": "大连", "key": API_KEY}},
    {"name": "[舆图] 舆图目录详情", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/yutu/detail", "params": {
        "instanceUri": "http://data.library.sh.cn/yutu/resource/instance/0bz3gu4famvcmlls",
        "key": API_KEY}},
    {"name": "[手迹] 南湖革命纪念馆手迹列表", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/shouji/list",
     "params": {"creator": "郭沫若", "pageSize": 1, "key": API_KEY}},
    {"name": "[手迹] 南湖革命纪念馆手迹详情", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/shouji/detail", "params": {
        "uri": "http://data.library.sh.cn/shouji/resource/photo/5q1co8xb5xjdwbro",
        "key": API_KEY}},
    {"name": "[红色旅游] 红色旅游建筑列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/gmwx/webapi/architecture/getArchitectures",
     "params": {"isRed": "1", "freetext": "刘长胜", "key": API_KEY}},
    {"name": "[红色旅游] 红色旅游建筑详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/gmwx/webapi/architecture/getArchitectureDetail",
     "params": {
         "uri": "http://data.library.sh.cn/entity/architecture/06w7n6cjlkuypjsx",
         "key": API_KEY}},
    {"name": "[关联书目] 作品列表", "method": "GET",
     "url": "https://data1.library.sh.cn/bib/webapi/work/list",
     "params": {"freetext": "建筑", "key": API_KEY}},
    {"name": "[关联书目] 作品详情", "method": "GET",
     "url": "https://data1.library.sh.cn/bib/webapi/work/detail", "params": {
        "uri": "http://bib.library.sh.cn/resource/work/ros0is65vccsu0yb",
        "key": API_KEY}},
    {"name": "[关联书目] 书目列表", "method": "GET",
     "url": "https://data1.library.sh.cn/bib/webapi/instance/list",
     "params": {"freetext": "传感器与信号处理", "key": API_KEY}},
    {"name": "[关联书目] 书目详情", "method": "GET",
     "url": "https://data1.library.sh.cn/bib/webapi/instance/detail",
     "params": {
         "uri": "http://bib.library.sh.cn/resource/instance/002bxotbf2dvsmxe",
         "key": API_KEY}},
    {"name": "[事件] 事件知识库列表", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/hsly/route/getEventList",
     "params": {"eventFreeText": "张善孖", "key": API_KEY}},
    {"name": "[事件] 事件知识库详情", "method": "GET",
     "url": "https://data1.library.sh.cn/webapi/hsly/route/getEventDetail",
     "params": {
         "uri": "http://data.library.sh.cn/authority/event/0ukxgwxbuasfnf6p",
         "key": API_KEY}},
    {"name": "[地名志] 上海地名志列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dmz/webapi/geonames/list",
     "params": {"type": "1", "freetext": "白龙港", "key": API_KEY}},
    {"name": "[地名志] 上海地名志详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dmz/webapi/geonames/detail",
     "params": {
         "uri": "http://data.library.sh.cn/dmz/entity/place/37vqhqhbwdubwshn",
         "key": API_KEY}},
    {"name": "[地名志] 相关道路列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/wkl/webapi/road/list",
     "params": {"type": "2", "freetext": "万安街", "key": API_KEY}},
    {"name": "[武康路] 建筑列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/wkl/webapi/building/list",
     "params": {"freetext": "武康路", "key": API_KEY}},
    {"name": "[武康路] 道路列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/wkl/webapi/road/list",
     "params": {"freetext": "武康", "key": API_KEY}},
    {"name": "[武康路] 建筑事件列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/wkl/webapi/building/event/list",
     "params": {
         "buri": "http://data.library.sh.cn/entity/architecture/yyknd1unz1xonxp7",
         "key": API_KEY}},
    {"name": "[武康路] 建筑详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/wkl/webapi/building/detail",
     "params": {
         "uri": "http://data.library.sh.cn/entity/architecture/4i58zbd2c3ribkcd",
         "key": API_KEY}},
    {"name": "[武康路] 道路详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/wkl/webapi/road/detail",
     "params": {"uri": "http://data.library.sh.cn/entity/road/h7h5umwxwozgates",
                "key": API_KEY}},
    {"name": "[武康路] 人物详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/wkl/webapi/persons/detail",
     "params": {
         "uri": "http://data.library.sh.cn/entity/person/6pnc6xdap3cfkcup",
         "key": API_KEY}},
    {"name": "[武康路] 相关人物列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/wkl/webapi/persons/list",
     "params": {"pname": "黄兴", "key": API_KEY}},
    {"name": "[电影] 电影列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/movie/getMovie",
     "params": {"video": "松花江上", "key": API_KEY}},
    {"name": "[电影] 电影详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/movie/movieDetail",
     "params": {
         "uri": "http://data.library.sh.cn/dy/resource/movie/612x1xoyxtzxuvaf",
         "key": API_KEY}},
    {"name": "[电影] 视频详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/video/videoDetail",
     "params": {
         "uri": "http://data.library.sh.cn/dy/resource/video/qzwpdwkeany4pp5r",
         "key": API_KEY}},
    {"name": "[电影] 照片详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/photo/photoDetail",
     "params": {
         "uri": "http://data.library.sh.cn/dy/resource/photo/ydyxfnac33hvflz0",
         "key": API_KEY}},
    {"name": "[电影] 照片列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/photo/getPhotoList",
     "params": {"type": "剧照", "date": "1935", "key": API_KEY}},
    {"name": "[电影] 音乐详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/music/musicDetail",
     "params": {
         "uri": "http://data.library.sh.cn/dy/resource/music/gdyr538dl6lfcck0",
         "key": API_KEY}},
    {"name": "[电影] 音乐列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/music/getMusicList",
     "params": {"name": "塞上风", "date": "1940", "key": API_KEY}},
    {"name": "[电影] 期刊列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/magazine/getMagazineList",
     "params": {"foafname": "美术电影", "key": API_KEY}},
    {"name": "[电影] 期刊详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/magazine/magazineDetail",
     "params": {
         "uri": "http://data.library.sh.cn/dy/resource/magazine/37ajafgt453gvsx3",
         "key": API_KEY}},
    {"name": "[电影] 期刊篇章列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/artical/getArticalList",
     "params": {"title": "无锡", "key": API_KEY}},
    {"name": "[电影] 书影列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/picture/getPictureList",
     "params": {"name": "明星特刊", "key": API_KEY}},
    {"name": "[电影] 获取期刊篇章出版年", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/magazine/getPzYearOfMag",
     "params": {
         "uri": "http://data.library.sh.cn/dy/resource/magazine/t3wnqk4yu2tleczl",
         "key": API_KEY}},
    {"name": "[电影] 获取期刊篇章卷期", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/magazine/getPzJuanqiOfMag",
     "params": {"year": "1931",
                "uri": "http://data.library.sh.cn/dy/resource/magazine/t3wnqk4yu2tleczl",
                "key": API_KEY}},
    {"name": "[电影] 根据期刊获取篇章列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/magazine/getPzListOfMag",
     "params": {"juanqi": "1931,1(25)",
                "uri": "http://data.library.sh.cn/dy/resource/magazine/t3wnqk4yu2tleczl",
                "key": API_KEY}},
    {"name": "[电影] 戏院详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/architecture/architectureDetail",
     "params": {
         "uri": "http://data.library.sh.cn/entity/theater/g2n5f6cpkqkaxygj",
         "key": API_KEY}},
    {"name": "[电影] 影人详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/person/personDetailAll",
     "params": {
         "uri": "http://data.library.sh.cn/entity/person/emfzhg6fzke4tzs9",
         "key": API_KEY}},
    {"name": "[电影] 获取联想词列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/movie/getAutoComList",
     "params": {"graph": "http://dy.library.sh.cn/graph/movie",
                "className": "shl:Movie", "p": "foaf:name", "o": "三",
                "key": API_KEY}},
    {"name": "[电影] 视频列表", "method": "POST",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/video/getVideoList",
     "params": {"title": "马路天使", "key": API_KEY}},
    {"name": "[电影] 电影首页海报", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/movie/getHomeFilmBillList",
     "params": {"key": API_KEY}},
    {"name": "[电影] 影剧院列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/dydata/webapi/architecture/getArchitecture",
     "params": {"freetext": "上海大戏院", "key": API_KEY}},
    {"name": "[革命文献] 革命文献书目列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/gmwx/webapi/instance/search",
     "params": {"freetext": "郭沫若", "key": API_KEY}},
    {"name": "[革命文献] 革命文献书目详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/gmwx/webapi/instance/detail",
     "params": {
         "uri": "http://data.library.sh.cn/gmwx/resource/instance/00y5u3c6f033nwlm",
         "key": API_KEY}},
    {"name": "[革命文献] 作品列表", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/gmwx/webapi/work/search",
     "params": {"freetext": "郭沫若", "key": API_KEY}},
    {"name": "[革命文献] 作品详情", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/gmwx/webapi/work/detail",
     "params": {
         "uri": "http://data.library.sh.cn/gmwx/resource/work/0hq476jyfhdh5s8r",
         "key": API_KEY}},
    {"name": "[革命文献] 地图检索", "method": "GET",
     "url": "https://data1.library.sh.cn/shnh/gmwx/webapi/instance/placeInArea",
     "params": {"points": "POLYGON((102.6 31.6,115.0 29.0,107.1 25.1))",
                "freetext": "共产党", "key": API_KEY}},
    {"name": "[古籍] 古籍实例列表", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/instances",
     "params": {"key": API_KEY, "freetext": "三国"}},
    {"name": "[古籍] 古籍实例详情", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/instanceInfo",
     "params": {"key": API_KEY,
                "uri": "http://data.library.sh.cn/gj/resource/instance/daxcp61j62sx260a"}},
    {"name": "[古籍] 古籍馆藏信息", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/items",
     "params": {"key": API_KEY,
                "uri": "http://data.library.sh.cn/gj/resource/instance/cs5colfieikc3kqe"}},
    {"name": "[古籍] 古籍作品列表", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/works",
     "params": {"key": API_KEY, "title": "三国"}},
    {"name": "[古籍] 古籍作品责任者列表", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/workPersons",
     "params": {"key": API_KEY,
                "uri": "http://data.library.sh.cn/gj/resource/work/qy7i08368s4oae81"}},
    {"name": "[古籍] 古籍作品详情", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/workInfo",
     "params": {"key": API_KEY,
                "uri": "http://data.library.sh.cn/gj/resource/work/qy7i08368s4oae81"}},
    {"name": "[古籍] 古籍源流列表", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/annotations",
     "params": {"key": API_KEY, "workTitle": "三国", "source": "11"}},
    {"name": "[古籍] 古籍分类列表", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/classificationList",
     "params": {"key": API_KEY, "source": "6", "fUri": "-1",
                "isLoop": "false"}},
    {"name": "[古籍] 根据作品获取相关实例", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/instancesDisplayInfo",
     "params": {"key": API_KEY,
                "uri": "http://data.library.sh.cn/gj/resource/work/4rapf3lohdqcicr6"}},
    {"name": "[古籍] 获取相关作者合作实例", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/hzInstances",
     "params": {"key": API_KEY,
                "personUri1": "http://data.library.sh.cn/entity/person/1x7xg5qx64m4baqp",
                "personUri2": "http://data.library.sh.cn/entity/person/8twhzro5ecysaqrc",
                "hzType": "2"}},
    {"name": "[印章] 印章列表", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/seals",
     "params": {"key": API_KEY, "freeText": "宋"}},
    {"name": "[印章] 印章详情", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/sealDetail",
     "params": {"key": API_KEY,
                "sealimg": "http://img.library.sh.cn/gj/seal/3f8tdaruvtz3ym4m.jpg"}},
    {"name": "[印章] 藏书楼列表", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/libliotheca",
     "params": {"key": API_KEY, "freeText": "藏书楼"}},
    {"name": "[印章] 藏书家列表", "method": "GET",
     "url": "https://data1.library.sh.cn/gj/webapi/sealOwnerList",
     "params": {"key": API_KEY, "freeText": "黄丕烈"}},
    {"name": "[家谱] 姓氏查询", "method": "GET",
     "url": "https://data1.library.sh.cn/jp/familyname/陈",
     "params": {"key": API_KEY}},
    {"name": "[家谱] 先祖名人查询", "method": "GET",
     "url": "https://data1.library.sh.cn/jp/person/data",
     "params": {"personName": "胡昌翼", "key": API_KEY}},
    {"name": "[家谱] 家谱谱目查询", "method": "GET",
     "url": "https://data1.library.sh.cn/jp/work/data",
     "params": {"title": "上川", "key": API_KEY}},
    {"name": "[基础] 人物列表-高级检索", "method": "GET",
     "url": "https://data1.library.sh.cn/persons/data",
     "params": {"fname": "巴金", "key": API_KEY}},
    {"name": "[基础] 地名检索", "method": "GET",
     "url": "https://data1.library.sh.cn/place/杞县",
     "params": {"key": API_KEY}},
    {"name": "[基础] 朝代列表", "method": "GET",
     "url": "https://data1.library.sh.cn/temporal.json",
     "params": {"key": API_KEY}},
    {"name": "[基础] 馆藏机构列表", "method": "POST",
     "url": "https://data1.library.sh.cn/organization/search",
     "params": {"freeText": "上图", "firstChar": "全部", "pageth": "1",
                "key": API_KEY}},
]

def get_all_apis():
    """获取所有API定义"""
    return API_DEFINITIONS
